version: '3'

vars:
  PLUGINS_DIR: plugins
  COLLECTIONS_DIR: collections

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  # =============================================================================
  # Development
  # =============================================================================

  list:plugins:
    desc: List all plugins
    cmds:
      - ls -1 {{.PLUGINS_DIR}}

  list:collections:
    desc: List all collections
    cmds:
      - ls -1 {{.COLLECTIONS_DIR}}

  # =============================================================================
  # Clipboard helpers (for deploying to Thymer)
  # =============================================================================

  copy:plugin:
    desc: Copy a plugin to clipboard (usage - task copy:plugin -- github)
    cmds:
      - cat {{.PLUGINS_DIR}}/{{.CLI_ARGS}}/plugin.js | wl-copy
      - echo "Copied {{.CLI_ARGS}}/plugin.js to clipboard"

  copy:collection:
    desc: Copy a collection schema to clipboard (usage - task copy:collection -- issues)
    cmds:
      - cat {{.COLLECTIONS_DIR}}/{{.CLI_ARGS}}/collection.json | wl-copy
      - echo "Copied {{.CLI_ARGS}}/collection.json to clipboard"

  copy:synchub:
    desc: Copy Sync Hub plugin to clipboard
    cmds:
      - cat synchub/plugin.js | wl-copy
      - echo "Copied synchub/plugin.js to clipboard"

  copy:synchub:collection:
    desc: Copy Sync Hub collection schema to clipboard
    cmds:
      - cat synchub/collection.json | wl-copy
      - echo "Copied synchub/collection.json to clipboard"

  # =============================================================================
  # File paths (when clipboard doesn't work)
  # =============================================================================

  path:plugin:
    desc: Print plugin file path (usage - task path:plugin -- github)
    cmds:
      - realpath {{.PLUGINS_DIR}}/{{.CLI_ARGS}}/plugin.js

  path:collection:
    desc: Print collection schema path (usage - task path:collection -- issues)
    cmds:
      - realpath {{.COLLECTIONS_DIR}}/{{.CLI_ARGS}}/collection.json

  # =============================================================================
  # New plugin scaffolding
  # =============================================================================

  new:plugin:
    desc: Create a new plugin from template (usage - task new:plugin -- my-plugin)
    cmds:
      - cp -r {{.PLUGINS_DIR}}/_template {{.PLUGINS_DIR}}/{{.CLI_ARGS}}
      - echo "Created {{.PLUGINS_DIR}}/{{.CLI_ARGS}}/"
      - echo "Edit plugin.js and plugin.json to customize"

  new:collection:
    desc: Create a new collection (usage - task new:collection -- my-collection)
    cmds:
      - mkdir -p {{.COLLECTIONS_DIR}}/{{.CLI_ARGS}}
      - |
        cat > {{.COLLECTIONS_DIR}}/{{.CLI_ARGS}}/collection.json << 'EOF'
        {
          "ver": 1,
          "name": "{{.CLI_ARGS}}",
          "icon": "ti-folder",
          "home": false,
          "page_field_ids": [],
          "item_name": "Item",
          "description": "Description here",
          "show_sidebar_items": true,
          "show_cmdpal_items": true,
          "fields": [
            {
              "icon": "ti-id",
              "id": "external_id",
              "label": "External ID",
              "type": "text",
              "read_only": true,
              "active": true
            }
          ],
          "sidebar_record_sort_dir": "desc",
          "sidebar_record_sort_field_id": "created_at",
          "managed": {"fields": false, "views": false, "sidebar": false},
          "custom": {},
          "views": []
        }
        EOF
      - echo "Created {{.COLLECTIONS_DIR}}/{{.CLI_ARGS}}/collection.json"

  # =============================================================================
  # Git shortcuts
  # =============================================================================

  status:
    desc: Git status
    cmds:
      - git status

  diff:
    desc: Git diff
    cmds:
      - git diff

  push:
    desc: Git push
    cmds:
      - git push

  # =============================================================================
  # Documentation
  # =============================================================================

  docs:
    desc: Show plugin creation guide
    cmds:
      - cat CREATING_PLUGINS.md

  # =============================================================================
  # Validation
  # =============================================================================

  validate:json:
    desc: Validate all collection.json files
    cmds:
      - |
        for f in {{.COLLECTIONS_DIR}}/*/collection.json synchub/collection.json; do
          echo "Validating $f..."
          python3 -m json.tool "$f" > /dev/null && echo "  ✓ Valid" || echo "  ✗ Invalid"
        done

  validate:plugins:
    desc: Check plugin.json files exist and are valid
    cmds:
      - |
        for d in {{.PLUGINS_DIR}}/*/; do
          name=$(basename "$d")
          if [ "$name" = "_template" ]; then continue; fi

          if [ -f "$d/plugin.json" ]; then
            echo "✓ $name/plugin.json exists"
            python3 -m json.tool "$d/plugin.json" > /dev/null || echo "  ✗ Invalid JSON"
          else
            echo "✗ $name/plugin.json missing"
          fi

          if [ -f "$d/plugin.js" ]; then
            echo "✓ $name/plugin.js exists"
          else
            echo "✗ $name/plugin.js missing"
          fi
        done

  validate:versions:
    desc: Check that JS and JSON versions match
    silent: true
    cmds:
      - |
        echo "🔍 Checking version consistency..."
        echo ""
        ERRORS=0

        # Check plugins
        for d in {{.PLUGINS_DIR}}/*/; do
          name=$(basename "$d")
          if [ "$name" = "_template" ]; then continue; fi

          js_file="$d/plugin.js"
          json_file="$d/plugin.json"

          if [ -f "$js_file" ] && [ -f "$json_file" ]; then
            js_ver=$(grep "^const VERSION = " "$js_file" | sed "s/.*= ['\"]v\?\([^'\"]*\)['\"].*/\1/")
            json_ver=$(python3 -c "import json; print(json.load(open('$json_file')).get('version', 'MISSING'))" 2>/dev/null)

            if [ "$json_ver" = "MISSING" ]; then
              echo "⚠️  $name: JSON missing version field"
              ERRORS=$((ERRORS+1))
            elif [ "$js_ver" != "$json_ver" ]; then
              echo "✗ $name: JS=$js_ver JSON=$json_ver"
              ERRORS=$((ERRORS+1))
            else
              echo "✓ $name: $js_ver"
            fi
          fi
        done

        # Check collections
        for d in {{.COLLECTIONS_DIR}}/*/; do
          name=$(basename "$d")

          js_file="$d/plugin.js"
          json_file="$d/collection.json"

          if [ -f "$js_file" ] && [ -f "$json_file" ]; then
            js_ver=$(grep "^const VERSION = " "$js_file" | sed "s/.*= ['\"]v\?\([^'\"]*\)['\"].*/\1/")
            json_ver=$(python3 -c "import json; print(json.load(open('$json_file')).get('version', 'MISSING'))" 2>/dev/null)

            if [ "$json_ver" = "MISSING" ]; then
              echo "⚠️  collections/$name: JSON missing version field"
              ERRORS=$((ERRORS+1))
            elif [ "$js_ver" != "$json_ver" ]; then
              echo "✗ collections/$name: JS=$js_ver JSON=$json_ver"
              ERRORS=$((ERRORS+1))
            else
              echo "✓ collections/$name: $js_ver"
            fi
          fi
        done

        # Check synchub
        if [ -f "synchub/plugin.js" ] && [ -f "synchub/collection.json" ]; then
          js_ver=$(grep "^const VERSION = " "synchub/plugin.js" | sed "s/.*= ['\"]v\?\([^'\"]*\)['\"].*/\1/")
          json_ver=$(python3 -c "import json; print(json.load(open('synchub/collection.json')).get('version', 'MISSING'))" 2>/dev/null)

          if [ "$json_ver" = "MISSING" ]; then
            echo "⚠️  synchub: JSON missing version field"
            ERRORS=$((ERRORS+1))
          elif [ "$js_ver" != "$json_ver" ]; then
            echo "✗ synchub: JS=$js_ver JSON=$json_ver"
            ERRORS=$((ERRORS+1))
          else
            echo "✓ synchub: $js_ver"
          fi
        fi

        echo ""
        if [ $ERRORS -gt 0 ]; then
          echo "❌ $ERRORS version mismatches found"
          exit 1
        else
          echo "✅ All versions match!"
        fi

  # =============================================================================
  # Release Management
  # =============================================================================

  release:
    desc: Create a release (usage - task release -- v1.2.0)
    silent: true
    cmds:
      - |
        VERSION="{{.CLI_ARGS}}"
        if [ -z "$VERSION" ]; then
          echo "Usage: task release -- v1.2.0"
          exit 1
        fi

        # Validate version format
        if ! echo "$VERSION" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Error: Version must be in format v1.2.3"
          exit 1
        fi

        echo "🚀 Creating release $VERSION"
        echo ""

        # 1. Update VERSION file
        echo "$VERSION" > VERSION
        echo "✓ Updated VERSION file"

        # 2. Update version in all plugin .js files
        echo "✓ Updating version in JS files..."
        VERSION_NUM="${VERSION#v}"  # Strip 'v' prefix for JSON

        # Find all plugin.js files and add/update version constant
        for f in synchub/plugin.js \
                 agenthub/plugin.js \
                 habithub/plugin.js \
                 {{.COLLECTIONS_DIR}}/*/plugin.js \
                 {{.PLUGINS_DIR}}/*/plugin.js; do
          if [ -f "$f" ] && ! echo "$f" | grep -q "_template"; then
            # Check if VERSION constant exists, update or add it
            if grep -q "^const VERSION = " "$f"; then
              sed -i "s/^const VERSION = .*/const VERSION = '$VERSION';/" "$f"
            else
              # Add after 'use strict' or at top
              if grep -q "'use strict'" "$f"; then
                sed -i "/'use strict'/a const VERSION = '$VERSION';" "$f"
              else
                sed -i "1i const VERSION = '$VERSION';" "$f"
              fi
            fi
            echo "  ✓ $f"
          fi
        done

        # 3. Update version in all JSON files
        echo "✓ Updating version in JSON files..."

        # Plugin JSON files
        for f in {{.PLUGINS_DIR}}/*/plugin.json; do
          if [ -f "$f" ] && ! echo "$f" | grep -q "_template"; then
            python3 -c "
        import json
        with open('$f', 'r') as file:
            data = json.load(file)
        data['version'] = '$VERSION_NUM'
        with open('$f', 'w') as file:
            json.dump(data, file, indent=2)
            file.write('\n')
        "
            echo "  ✓ $f"
          fi
        done

        # Collection JSON files
        for f in {{.COLLECTIONS_DIR}}/*/collection.json synchub/collection.json agenthub/collection.json habithub/collection.json; do
          if [ -f "$f" ]; then
            python3 -c "
        import json
        with open('$f', 'r') as file:
            data = json.load(file)
        data['version'] = '$VERSION_NUM'
        with open('$f', 'w') as file:
            json.dump(data, file, indent=4)
            file.write('\n')
        "
            echo "  ✓ $f"
          fi
        done

        # 4. Git commit
        echo ""
        git add -A
        git commit -m "Release $VERSION"
        echo "✓ Committed changes"

        # 5. Git tag
        git tag "$VERSION"
        echo "✓ Created tag $VERSION"

        # 6. Push
        git push origin master --tags
        echo "✓ Pushed to origin"

        # 7. Create zip bundle
        ZIPNAME="thymer-synchub-$VERSION.zip"
        echo ""
        echo "📦 Creating $ZIPNAME..."

        zip -r "$ZIPNAME" \
          VERSION \
          synchub/ \
          agenthub/ \
          habithub/ \
          {{.COLLECTIONS_DIR}}/ \
          {{.PLUGINS_DIR}}/ \
          -x "*.git*" \
          -x "*/_template/*" \
          -x "*/node_modules/*"

        echo "✓ Created $ZIPNAME"

        # 8. Create GitHub release
        echo ""
        echo "📢 Creating GitHub release..."
        gh release create "$VERSION" "$ZIPNAME" \
          --title "$VERSION" \
          --generate-notes

        echo ""
        echo "✅ Release $VERSION complete!"
        echo "   https://github.com/riclib/thymer-synchub/releases/tag/$VERSION"

        # Cleanup
        rm "$ZIPNAME"

  release:dry-run:
    desc: Preview what release would do (usage - task release:dry-run -- v1.2.0)
    silent: true
    cmds:
      - |
        VERSION="{{.CLI_ARGS}}"
        if [ -z "$VERSION" ]; then
          echo "Usage: task release:dry-run -- v1.2.0"
          exit 1
        fi

        echo "🔍 Dry run for release $VERSION"
        echo ""
        echo "Would update VERSION file to: $VERSION"
        echo ""
        echo "Would update version in:"
        for f in synchub/plugin.js \
                 agenthub/plugin.js \
                 habithub/plugin.js \
                 {{.COLLECTIONS_DIR}}/*/plugin.js \
                 {{.PLUGINS_DIR}}/*/plugin.js; do
          if [ -f "$f" ] && ! echo "$f" | grep -q "_template"; then
            echo "  - $f"
          fi
        done
        echo ""
        echo "Would create: thymer-synchub-$VERSION.zip"
        echo "Would commit, tag $VERSION, and push"
        echo "Would create GitHub release $VERSION"

  version:
    desc: Show current version
    cmds:
      - cat VERSION
